apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::730335359268:role/GitHubActionsCICDrole
      username: github-actions
      groups:
        - system:masters
