apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: nodejs-app
type: Opaque
stringData:
  DB_CONNECTION_STRING: "postgres://milestone:L()]2~qSku3M$}M)FNSaq1xV+%[m@reviews-app-db.cresqccmg7d6.us-east-1.rds.amazonaws.com/ReviewsAppData"
#