apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-ingress-clusterrole
rules:
- apiGroups:
    - ""
    - "extensions"
  resources:
    - "configmaps"
    - "endpoints"
    - "events"
    - "ingresses"
    - "ingresses/status"
    - "services"
  verbs:
    - "create"
    - "get"
    - "list"
    - "update"
    - "watch"
    - "delete"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nginx-ingress-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: ingress-nginx  # Replace with your desired namespace
roleRef:
  kind: ClusterRole
  name: nginx-ingress-clusterrole  # Name of the ClusterRole created earlier
  apiGroup: rbac.authorization.k8s.io
