{{- if .Values.ingress.create }} # added so ingress is not created for backend
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "ingress-{{ .Values.applicationName }}"
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Values.applicationName }}-svc"
            port: 
              number: {{ .Values.service.port }}
  ingressClassName: nginx


  {{- end }}