apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.applicationName }}-svc"
  labels:
    app: {{ .Values.applicationName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      # targetPort: {{ .Values.service.targetport }} - not needed for ClusterIp
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.applicationName }}