applicationName: api-backend
replicaCount: 2
image:
  repository: 730335359268.dkr.ecr.us-east-1.amazonaws.com/nodejs-backend
  tag: ""
  pullPolicy: IfNotPresent
port: 3000
service:
  type: ClusterIP
  port: 80
  targetport: 3000
env:
  - name: PORT
    value: "3000"
envFromSecret: db-credentials
# hostname: reviews-api-dev.atrubin.click
#
