applicationName: nodejs-backend
replicaCount: 2
image:
  repository: 730335359268.dkr.ecr.us-east-1.amazonaws.com/apirepo
  tag: 0.1
pullPolicy: ifNotPresent
port: 3000

env:
  name: DB 
  value: postgres://vss:Cxj%5Bc4%7D7jeNdP%5D-3h%3C3Sho2-o9%3C%3F@vssdatabase.cf42a02yquzi.us-east-1.rds.amazonaws.com:5432/eksdatabase

  # 'postgresql://vss:Cxj[c4}7jeNdP]-3h<3Sho2-o9<?@vssdatabase.cf42a02yquzi.us-east-1.rds.amazonaws.com:5432/eksdatabase'

service:
  type: ClusterIP
  port: 3000
  targetport: 3000

ingress:
  create: false