applicationName: nodejs-frontend
replicaCount: 1
image:
  repository: 730335359268.dkr.ecr.us-east-1.amazonaws.com/nodejsapp
  tag: 0.1
pullPolicy: ifNotPresent
port: 80
env:
  name: API_HOST
  value: "http://nodejs-backend-svc:3000"
service:
  type: ClusterIP
  port: 80
  targetport: 80

ingress:
  create: true
  hostname: vss.click