applicationName: nodejs-frontend
replicaCount: 2
image:
  repository: 730335359268.dkr.ecr.us-east-1.amazonaws.com/nodejsapp
  tag: 0.1
pullPolicy: ifNotPresent
port: 80
env:
  key: http://nodejs-backend-svc
  name: "API_HOST"
service:
  type: ClusterIP
  port: 80

ingress:
  create: true
  hostname: vss.click