name: NodeJs Deployment Workflow

on:
  push:
    branches: ["*"]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ (github.ref == 'refs/heads/main' && 'dev') || (github.ref == 'refs/heads/prod' && 'production') }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: "us-east-1"

      - name: Login to ECR
        id: login-to-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push frontend docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-to-ecr.outputs.registry }}
          REPOSITORY: nodejsapp
          IMAGE_TAG: 0.1
        working-directory: ./web
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      # Uncomment to build, tag, and push backend docker image to Amazon ECR
      # - name: Build, tag, and push Backend docker image to Amazon ECR
      #   env:
      #     REGISTRY: ${{ steps.login-to-ecr.outputs.registry }}
      #     REPOSITORY: apirepo
      #     IMAGE_TAG: 0.1
      #   working-directory: ./api
      #   run: |
      #     docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
      #     docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Login to EKS
        run: aws eks update-kubeconfig --region us-east-1 --name project-x-dev

      - name: Create namespace
        run: kubectl create namespace sample-app || true

      - name: Install NGINX Ingress Controller
        run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.1/deploy/static/provider/cloud/deploy.yaml

      - name: Deploy frontend and service for it
        run: kubectl apply -f node-js-app/front.yaml

      - name: Deploy backend and service for it
        run: kubectl apply -f node-js-app/back.yaml

      - name: Deploy database and service for it
        run: kubectl apply -f node-js-app/database.yaml

      - name: Apply ingress rules
        run: kubectl apply -f node-js-app/ingress.yaml

      # Uncomment to use Helm for deployment
      # - name: Deploy frontend
      #   run: helm upgrade --install node-js-app ./node-js-app/ --values ./node-js-app/values/frontend.yaml --namespace sample-app

      # - name: Deploy backend
      #   run: |
      #     helm upgrade --install node-js-api ./node-js-app/ --values ./node-js-app/values/backend.yaml --namespace sample-app

      # apply service file through kubectl apply
      # apply ingress rules file through kubectl apply
      # see what happens
