name: NodeJs Deployment Workflow

on:
  push:
    branches: ["*"]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ (github.ref == 'refs/heads/main' && 'dev') || (github.ref == 'refs/heads/prod' && 'production') }}

    steps:
      - name: AWS Loggin
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: "us-east-1"

      - name: Clone repo
        uses: actions/checkout@v4

      - name: Login to ECR
        id: login-to-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Login to EKS
        run: aws eks update-kubeconfig --region us-east-1 --name project-x-dev

      - name: Create namespace
        run: kubectl create namespace sample-app || true

      - name: Deploy frontend with Helm
        run: |
          helm upgrade --install nodejs-frontend ./helm-chart --values ./helm-chart/values/frontend/dev-value.yaml --namespace sample-app
        env:
          HELM_DEBUG: "true"

      - name: Deploy backend with Helm
        run: |
          helm upgrade --install nodejs-backend ./helm-chart --values ./helm-chart/values/backend/dev-value.yaml --namespace sample-app
        env:
          HELM_DEBUG: "true"

  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: AWS Loggin
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: "us-east-1"

      - name: Login to EKS
        run: aws eks update-kubeconfig --region us-east-1 --name project-x-dev

      - name: Destroy frontend deployment
        run: helm uninstall nodejs-frontend --namespace sample-app || true

      - name: Destroy backend deployment
        run: helm uninstall nodejs-backend --namespace sample-app || true

      - name: Delete namespace
        run: kubectl delete namespace sample-app || true

      - name: Logout from ECR
        run: aws ecr logout --region us-east-1
